name: CI
on:
 pull_request:
 branches: [ main ]

jobs:
   testes:
     runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - nome: Instalar dependencias
      run: npm install
    - nome: Rodar os testes
      run: npm test
      